### ISSUE TITLE
A2OJ Ladder 11 problems

### ISSUE THREAD

**Issue by thunderfreak** [animeshbhakat/a2oj_solutions#1]
I would love to add some more solutions to problems belonging to A2OJ ladder 11 (div 2A problems) under #hacktoberfest2021
Let me know if you're interested!

**Comment by animeshbhakat** [comment]
Hey @thunderfreak . Feel free to contribute this this repo,

**Comment by thunderfreak** [comment]
Hey thanks! Will do so
